//emulates browser request url

### Test GET Home page
GET http://localhost:8383 

### Test GET Dashboard page
GET http://localhost:8383/dashboard

### Test GET getHomeInfo
GET http://localhost:8383/api/getHomeInfo

### Test GET getDashboardInfo
GET http://localhost:8383/api/getDashboardInfo

//CRUD operations
### Test POST with req body
POST http://localhost:8383/api/data
Content-Type: application/json

{
    "name": "Deepthi",
    "age": 38,
    "dob": "07/19/1986"
}